#!/bin/bash
urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }
if [ -z "$1" ]
  then
    echo
    echo 'Please enter the package of the application you wish to export from the emulator. For example: host.exp.exponent'
    exit 1
fi
if [ -z "$2" ]
  then
    echo
    echo 'Please enter the path of the folder you wish to export from the emulator. For example: ExperienceData/%2540anonymous%252F/SQLite/'
    exit 1
fi
if [ -z "$3" ]
  then
    echo
    echo 'Please enter the path where files will be extracted from the selected folder.. For example: /home/SQLite/'
    exit 1
fi

actualDate=$(date +"%d%m%Y_%H%M%S")

directoryToExport="apps/${1}/f/$(urldecode "$2")*"
destinationDirectory="$3$actualDate"

echo 
echo 'Downloading Android Emulator Backup...'
echo 'Now unlock your device and confirm the backup operation...'
adb backup -noapk ${1} > /dev/null
echo

echo 'Decompressing Android Emulator Backup...'
dd if=backup.ab bs=1 skip=24 | python -c "import zlib,sys;sys.stdout.write(zlib.decompress(sys.stdin.read()))" | tar -xf -
echo 

echo
echo 'Moving the backup do destination directory...'
mkdir ${destinationDirectory}
mv $directoryToExport "${destinationDirectory}/"
echo 

echo 'Deleting the backup files...'
rm -rf apps/ && rm -rf backup.ab
echo

echo "Finished! -> $destinationDirectory"